export const DATA = [
  {
    id: 1,
    author: 'John Doe',
    title: 'Whispers of Eternity',
    body: "In the dimly lit room, Sarah felt a shiver down her spine. The words echoed in her mind, 'Whispers of eternity resonate in the silence of the night.' It was a phrase she had read in her favorite book by John Doe, an author known for weaving tales of mystery and magic.",
  },
  {
    id: 2,
    author: 'Jane Smith',
    title: 'Reflections in the Mirror',
    body: "As the raindrops tapped against the window pane, Mark found himself lost in the pages of 'Reflections in the Mirror' by Jane Smith. The author's prose painted vivid pictures of self-discovery and inner reflections, leaving a lasting impression on the reader's soul.",
  },
  {
    id: 3,
    author: 'Emily Johnson',
    title: 'Serenade of Shadows',
    body: "Amelia gazed at the moonlit sky, pondering the mysteries that unfolded in 'Serenade of Shadows' by Emily Johnson. Each page carried a melody of suspense, and the author's intricate storytelling left readers enchanted by the dance between light and shadow.",
  },
  {
    id: 4,
    author: 'David Anderson',
    title: 'Echoes of Tomorrow',
    body: "In the futuristic cityscape, Alex immersed himself in 'Echoes of Tomorrow' by David Anderson. The author's visionary narrative and compelling characters propelled readers into a world where echoes of the future resonated with the choices made in the present.",
  },
  {
    id: 5,
    author: 'Sophia Martinez',
    title: 'Whispers in the Garden',
    body: "Among the blooming flowers, Sophia Martinez wove a tale of love and secrets in 'Whispers in the Garden.' Readers strolled through the story's lush landscapes, savoring the fragrance of romance and the intrigue hidden beneath the petals.",
  },
  {
    id: 6,
    author: 'Thomas Baker',
    title: 'Silent Echoes',
    body: "In the quiet town of Silent Hollow, Thomas Baker penned 'Silent Echoes,' a mystery that unfolded like a puzzle. Each page turned revealed fragments of the past, and readers found themselves deciphering the whispers of long-forgotten secrets.",
  },
  {
    id: 7,
    author: 'Eva Mitchell',
    title: 'Dance of Shadows',
    body: "Eva Mitchell's 'Dance of Shadows' unfolded on the stage of a forgotten theater. The characters pirouetted through the pages, leaving imprints of their stories in the shadows. Readers became entranced by the rhythm of the narrative, a ballet of emotions.",
  },
  {
    id: 8,
    author: 'Christopher Turner',
    title: 'Chronicles of the Cosmos',
    body: "In the vast expanse of the universe, Christopher Turner's 'Chronicles of the Cosmos' invited readers on an interstellar journey. Each chapter explored the cosmic tapestry, weaving together tales of distant galaxies and the interplay of celestial forces.",
  },
  {
    id: 9,
    author: 'Olivia White',
    title: 'The Enchanted Lighthouse',
    body: "At the edge of the cliff stood an ancient lighthouse, the setting for Olivia White's 'The Enchanted Lighthouse.' The beacon's light revealed hidden truths, and readers sailed through the mystic waves of the author's enchanting storytelling.",
  },
  {
    id: 10,
    author: 'Robert Adams',
    title: 'Ephemeral Whispers',
    body: "In the twilight of existence, Robert Adams penned 'Ephemeral Whispers,' a philosophical exploration of life's fleeting moments. Each chapter was a contemplative journey, and readers found solace in the delicate prose that lingered like a gentle breeze.",
  },
  {
    id: 11,
    author: 'Megan Johnson',
    title: 'The Midnight Carnival',
    body: "Beneath the moonlit sky, Megan Johnson's characters danced through 'The Midnight Carnival.' The carnival's magic unfolded in the shadows, and readers were swept away by the enchantment of the author's whimsical narrative.",
  },
  {
    id: 12,
    author: 'Samuel Roberts',
    title: 'Echoes of the Abyss',
    body: "In the depths of the unknown, Samuel Roberts explored 'Echoes of the Abyss.' The darkness held secrets, and readers ventured into the abyss alongside the author's characters, discovering the echoes of both fear and fascination.",
  },
  {
    id: 13,
    author: 'Grace Miller',
    title: 'A Symphony of Stars',
    body: "Across the celestial symphony, Grace Miller conducted 'A Symphony of Stars.' The night sky became a canvas, and readers traced the constellations of the author's imagination, where each star told a tale in the grand cosmic orchestra.",
  },
  {
    id: 14,
    author: 'Jonathan Taylor',
    title: 'The Quantum Paradox',
    body: "Within the quantum realm, Jonathan Taylor explored the enigma of existence in 'The Quantum Paradox.' The characters danced between parallel worlds, and readers were entangled in the author's web of intrigue and speculative wonder.",
  },
  {
    id: 15,
    author: 'Natalie Turner',
    title: 'Whispers of the Sea',
    body: "On the windswept shore, Natalie Turner's 'Whispers of the Sea' unfolded like waves upon the sand. The tide carried the secrets of the past, and readers immersed themselves in the ebb and flow of the author's maritime tale.",
  },
  {
    id: 16,
    author: 'Henry Lee',
    title: 'The Clockwork Kingdom',
    body: "In a realm of gears and cogs, Henry Lee crafted 'The Clockwork Kingdom.' The ticking of mechanical hearts echoed through the narrative, and readers marveled at the intricate world the author constructed with precision and imagination.",
  },
  {
    id: 17,
    author: 'Isabel Martinez',
    title: 'Mystic Moonlight',
    body: "Beneath the mystic moonlight, Isabel Martinez's characters embarked on a journey in 'Mystic Moonlight.' The night held secrets, and readers followed the author's enchanting prose through a tapestry woven with moonbeams and magic.",
  },
  {
    id: 18,
    author: 'Richard Adams',
    title: 'The Whispering Woods',
    body: "Amidst ancient trees, Richard Adams penned 'The Whispering Woods.' The rustle of leaves carried tales untold, and readers ventured deep into the heart of the forest, where the author's narrative wove a tale of mystery and ancient magic.",
  },
  {
    id: 19,
    author: 'Sophie Turner',
    title: 'Canvas of Dreams',
    body: "In the quiet art studio, Olivia found solace in the strokes of imagination painted on the 'Canvas of Dreams' by Sophie Turner. Each chapter unfolded a new layer of creativity, inspiring readers to embrace the beauty that lies within the colors of their own dreams.",
  },
  {
    id: 20,
    author: 'Daniel Evans',
    title: 'Ripples of Destiny',
    body: "In the small seaside town, Daniel Evans penned 'Ripples of Destiny,' a tale where every choice sent ripples through the fabric of fate. Readers sailed through the narrative, navigating the currents of uncertainty, and discovering that destiny is a tapestry woven by the choices we make.",
  },
  {
    id: 21,
    author: 'Emma Wright',
    title: 'The Forgotten Symphony',
    body: "In the attic of memories, Emma Wright composed 'The Forgotten Symphony.' Each note carried the weight of forgotten stories, and readers explored the author's melodic prose, rediscovering the echoes of the past within the forgotten tunes.",
  },
  {
    id: 22,
    author: 'Brian Johnson',
    title: 'Whispers in the Breeze',
    body: "On the hilltop, Brian Johnson's characters listened to 'Whispers in the Breeze.' The wind carried the tales of the meadow, and readers joined the characters in unraveling the secrets carried by the gentle caress of the author's narrative.",
  },
  {
    id: 23,
    author: 'Victoria Lee',
    title: 'Eternal Embers',
    body: "Burning brightly in the night, 'Eternal Embers' by Victoria Lee illuminated the path of forgotten legends. Readers traversed the realms of fantasy, where the author's characters became beacons in the darkness, guiding the way through the intricacies of a mythical world.",
  },
  {
    id: 24,
    author: 'Gabriel Miller',
    title: "The Alchemist's Legacy",
    body: "In a world of potions and mysteries, Gabriel Miller penned 'The Alchemist's Legacy.' The protagonist delved into the secrets of transmutation, and readers followed the author's alchemical narrative, where each chapter distilled the essence of magic and discovery.",
  },
  {
    id: 25,
    author: 'Lily Turner',
    title: 'The Enchanted Garden',
    body: "Amidst the blooming flowers, Lily Turner cultivated 'The Enchanted Garden.' Each petal held a story, and readers strolled through the author's botanical prose, discovering the magic that unfolded within the vibrant tapestry of nature.",
  },
  {
    id: 26,
    author: 'Connor Davis',
    title: 'Echoes of the Void',
    body: "In the cosmic silence, Connor Davis explored 'Echoes of the Void.' The vast expanse held echoes of forgotten tales, and readers traversed the celestial landscape alongside the author's characters, unraveling the mysteries hidden within the cosmic abyss.",
  },
  {
    id: 27,
    author: 'Sophia Turner',
    title: 'The Celestial Sonata',
    body: "Across the starlit symphony, Sophia Turner composed 'The Celestial Sonata.' Each celestial note resonated with cosmic tales, and readers embarked on a journey through the astral realms, guided by the harmonious prose of the author's interstellar composition.",
  },
  {
    id: 28,
    author: 'Nicholas Wright',
    title: 'Whispers of the Pines',
    body: "Beneath the towering pines, Nicholas Wright penned 'Whispers of the Pines.' The forest held secrets, and readers followed the trail of the author's characters, discovering the echoes of ancient stories carried by the gentle rustle of pine needles.",
  },
  {
    id: 29,
    author: 'Emma Turner',
    title: 'Luminous Dreams',
    body: "In the realm of dreams, Emma Turner painted 'Luminous Dreams.' Each dream held a shimmering tale, and readers journeyed through the author's surreal landscapes, where the boundaries between reality and imagination blurred in the soft glow of the dreamscape.",
  },
  {
    id: 30,
    author: 'Nathan Roberts',
    title: 'The Quantum Garden',
    body: "Amidst the quantum flora, Nathan Roberts cultivated 'The Quantum Garden.' The laws of reality bent in the author's narrative, and readers explored the intricate patterns of existence within the quantum blooms of the fantastical garden.",
  },
  {
    id: 31,
    author: 'Isabella Davis',
    title: 'Echoes of Elysium',
    body: "In the mythical realm of Elysium, Isabella Davis wove 'Echoes of Elysium.' The echoes carried the resonance of ancient legends, and readers embarked on a quest alongside the author's characters, discovering the magic that lingered in the mythical tapestry.",
  },
  {
    id: 32,
    author: 'William Turner',
    title: 'The Astral Odyssey',
    body: "Across the astral sea, William Turner navigated 'The Astral Odyssey.' Each chapter sailed through celestial currents, and readers ventured into the author's cosmic narrative, where the boundaries between reality and the astral realms blurred in the starlit voyage.",
  },
  {
    id: 33,
    author: 'Eva Turner',
    title: 'Whispers in the Meadow',
    body: "In the sunlit meadow, Eva Turner's characters listened to 'Whispers in the Meadow.' The gentle breeze carried tales of the wildflowers, and readers joined the characters in unraveling the secrets hidden within the rustling grasses of the author's narrative.",
  },
  {
    id: 34,
    author: 'Samuel Turner',
    title: 'The Forgotten Symphony',
    body: "In the attic of memories, Samuel Turner composed 'The Forgotten Symphony.' Each note held the weight of forgotten stories, and readers explored the melodic prose, rediscovering the echoes of the past within the haunting tunes of the author's forgotten symphony.",
  },
  {
    id: 35,
    author: 'Mia Roberts',
    title: "The Alchemist's Legacy",
    body: "In a world of potions and mysteries, Mia Roberts penned 'The Alchemist's Legacy.' The protagonist delved into the secrets of transmutation, and readers followed the alchemical narrative, where each chapter distilled the essence of magic and discovery.",
  },
  {
    id: 36,
    author: 'Lucas Davis',
    title: 'Echoes of the Void',
    body: "In the cosmic silence, Lucas Davis explored 'Echoes of the Void.' The vast expanse held echoes of forgotten tales, and readers traversed the celestial landscape alongside the author's characters, unraveling the mysteries hidden within",
  },
]
